### ISSUE TITLE
Subscribe to bulk feeds

### ISSUE THREAD

**Issue by AnasMostefaoui** [superfeedr/documentation#101]
Hello,

First, thanks a lot for superfeedr, it does help us saving huge amount of time and work.
We have a use case where we need to subscribe to bulk feeds, currently we are doing it by iterating  through feeds and send subscribe request for each bulk, and making 1 second between each request.
The issue is sometimes, the connection is closed (which make sense), is there any other clean way to do such thing ?

thanks

**Comment by pbirsinger** [comment]
This would be huge.
