### ISSUE TITLE
How to detect removed items?

### ISSUE THREAD

**Issue by jacob1237** [superfeedr/documentation#103]
Hello there,

This is more a question than an issue.
In my current work I need to detect what items were removed from the feed to be able to keep my database in sync (it is about podcasts).

Is there a simple way to detect removed items with SuperFeedr? For example a special notification type or something.

Thank you!

**Comment by julien51** [comment]
Hello, I am sorry for the delay to get back to you. Unfortunately at this point there is no mechanism in feeds to detect deleted entries.
