### ISSUE TITLE
help with rss feed

### ISSUE THREAD

**Issue by sthieu** [superfeedr/documentation#105]
I'm trying to subscribe to the following rss feed but its not returning any content
http://www.qjumpers.co.nz/rss/jobs/?organisationid=34

Results:
{
  "status": {
    "entriesCountSinceLastMaintenance": 0,
    "velocity": 0,
    "popularity": 0,
    "pornRank": 0,
    "bozoRank": 0,
    "lastParse": 1238466305,
    "period": 900,
    "lastMaintenanceAt": 1238466305,
    "lastFetch": 1238466305,
    "code": 0,
    "title": "Track feed for 'http://www.qjumpers.co.nz/rss/jobs/?organisationid=34'",
    "nextFetch": 1238466305,
    "http": ""
  },
  "title": "Track feed for 'http://www.qjumpers.co.nz/rss/jobs/?organisationid=34'",
  "updated": "",
  "standardLinks": {},
  "items": []
}

Any help is much appreciated.

**Comment by julien51** [comment]
Are you subscribed to that feed? If so please, share your superfeedr login (not password!). Thanks.

**Comment by sthieu** [comment]
Hi Julien,

My superfeedr login is Lancorpnz.
I have set up a subscription to the rss feed

Cheers,
Stefan
