### ISSUE TITLE
Broken link in documentation/subscribers.md

### ISSUE THREAD

**Issue by NorthDecoder** [superfeedr/documentation#108]
On line 144 of the file documentation/subscribers.md the following link to googlecode is broken:
**Our API is based on the [PubSubHubbub protocol](https://pubsubhubbub.googlecode.com/svn/trunk/pubsubhubbub-core-0.4.html) with a couple simplifications.**

Searching for _PubSubHubbub protocol_ turns up [github PubSubHubbub](https://github.com/pubsubhubbub/PubSubHubbub). It is unclear if that is the replacement repository that should be referenced.

**Comment by julien51** [comment]
Thanks.
