### ISSUE TITLE
Items in feed being excluded by sorting

### ISSUE THREAD

**Issue by BrendanAdkins** [superfeedr/documentation#109]
My Superfeedr username is xorphus. I have one subscription, to http://rewire.news/feed/, which I use to consume the feed items in json from a web app.

Recently the app began showing something strange--older entries would appear in place of new ones, mixed in with the new ones I expected. The feed had been recently fetched and its RSS checked out as valid. Upon examining the feed's details, I saw this:

PAST` ENTRIES' IDS (FEEDS ONLY):
https://rewire.news/?post_type=article&p=100305
https://rewire.news/?post_type=article&p=100322
https://rewire.news/?post_type=article&p=100320
https://rewire.news/?post_type=ablc_blog_post&p=100303
https://rewire.news/?post_type=article&p=100304
https://rewire.news/?post_type=article&p=100300
https://rewire.news/?post_type=article&p=100284
https://rewire.news/?post_type=article&p=100281
https://rewire.news/?post_type=article&p=100277
https://rewire.news/?post_type=article&p=100272

That lists ten recent articles that had been posted to the feed, in a vaguely but not entirely alpha/numeric sorting order. However, the ten articles actually present in the current feed have these guids:

https://rewire.news/?post_type=article&p=100305
https://rewire.news/?post_type=article&p=100322
https://rewire.news/?post_type=article&p=100241
https://rewire.news/?post_type=article&p=100307
https://rewire.news/?post_type=article&p=100320
https://rewire.news/?post_type=ablc_blog_post&#038;p=100303
https://rewire.news/?post_type=article&p=100304
https://rewire.news/?post_type=article&p=100300
https://rewire.news/?post_type=article&p=100284
https://rewire.news/?post_type=article&p=100281

The third and fourth entries have been mysteriously dropped and replaced at the bottom with older items. Is there some kind of issue with entries getting dropped if their ID is not sorted above a certain cutoff? If this behavior is intended, is there a way I can disable it?

**Comment by julien51** [comment]
This happens because some of the entries have been updated and we sort by last update...

**Comment by BrendanAdkins** [comment]
I take your point and I can adjust for that, but two of the items--the ones with IDs 100272 and 100277--were in the superfeedr json but NOT in the existing XML of the feed at the time. The RSS only contained ten posts. 100272 and 100277 were not in there anywhere; 100241 and 100307 were. Where would superfeedr have gotten the old entries if they were not in the XML?

**Comment by julien51** [comment]
So we cache all the feed's content up to 50 stories. 
Let's say the feed has 10 entries (1,2,3,4,5,6,7,8,9,10), and 10 is the "most recent", 1 is the oldest on day D.
On D+1, an new entry is added, so there are now 2,3,4,5,6,7,8,9,10,11... but superfeedr still has 1. So if you query for more than 10 elements you will have it.

Now, let's say 5 is updated later that day. If you pull the data for 10 entries from Superfeedr you will now see a feed with 2,3,4,6,7,8,9,10,11,5. Similarly whn 2 is updated, the fed bcomes 3,4,6,7,8,9,10,11,5,2.

On D+2, a new entry is added and when getting the data from Superfeedr the feed will be: 6,7,8,9,10,11,5,2,12. 2 is not in the original feed anymore, but Superfeedr still yields it when you request 10 entries.

**Comment by brendanapluscitizen** [comment]
Okay, this makes more sense. I was not aware of the caching. So it's possible to request and retrieve 50 entries from a feed even if the RSS itself only contains a max of 10 entries?

**Comment by brendanapluscitizen** [comment]
Here's a stripped-down version of my code (sans auth info). I'm using the jquery wrapper.

```
function fetchFeed() {
              
              var feed = new $.superfeedr.Feed('http://track.superfeedr.com/?query=site%3Arewire.news');
              feed.setNumEntries(50);
              feed.count = 50;
              console.log("count is "+feed.count);
              feed.setResultFormat('json');
              feed.load(function(result) {

                if (!result.error) {
                  console.log("there are "+result.feed.items.length+" entries");
                  for (var i = 0; i < result.feed.items.length; i++) {
                    var entry = result.feed.items[i];
                    $("#feed").html(entry.title);
                  }
                } else {
                    console.log(result.error.code);
                    console.log(result.error.message);
                }
              });
```

The result I see in the console:

```
count is 50
there are 10 entries
```

"there are 10 entries" appears whether I set the count variable to above or below 10, and indeed the page shows 10 headlines. Is that expected?

**Comment by julien51** [comment]
We can only return more than 10 if we have have more than 10 entries stored.
Taking the example above, if you asked for 50 stories on day D, you would only get 10 because we cannot store the entries from the previous days which we do not know about...
On D+1, you could get up to 11 elements... etc.

**Comment by brendanapluscitizen** [comment]
The entire reason for the existence of the ticket is that, in your words, superfeedr was caching more than 10 stories for this feed. Today has to be at least D+2 already. Why can I still only retrieve 10 stories, but then have to account for more than 10 stories reappearing from the cache when updated?

**Comment by julien51** [comment]
I see you are not subscribed to http://rewire.news/feed/... which you should probably start by doing.

**Comment by BrendanAdkins** [comment]
![screen shot 2017-03-23 at 7 51 32 am](https://cloud.githubusercontent.com/assets/630932/24253440/9bd68ad6-0f9d-11e7-9a1f-3e1a409ae700.png)

Is this not the same thing as subscribing to that feed? I cannot find any option on the dashboard to simply enter an RSS URL and subscribe to it directly.

**Comment by julien51** [comment]
This is because you created a tracker account... instead of a subscriber account.

**Comment by BrendanAdkins** [comment]
I had no idea there was a significant difference. Thank you for clarifying. I'll test this again and see if I am able to retrieve more cached entries tomorrow.

**Comment by BrendanAdkins** [comment]
Okay, the feed is behaving as expected now. Thank you.
