### ISSUE TITLE
Popular Feeds Question

### ISSUE THREAD

**Issue by curtins** [superfeedr/documentation#110]
I am trying to construct a query that identifies feeds with a popularity of > 5
curl https://push.superfeedr.com/ -X POST -u xxx:xxx -d'hub.mode=search' -d'?query=popularity>5'

This does not seem to be working. Can you please send me a complete query I can use to generate the list of popular feeds.

Thanks,
Steve

**Comment by julien51** [comment]
Steve, 
Thanks for reaching out. What errors are you seeing?
Thanks
