### ISSUE TITLE
Entire website down?

### ISSUE THREAD

**Issue by jamescridland** [superfeedr/documentation#112]
I've just tried logging in, to be rewarded with a 500 error on every page.

Please don't make me learn how to program the API... ;)

![screenshot 2017-03-29 at 11 02 31](https://cloud.githubusercontent.com/assets/231941/24433914/6a9938de-146f-11e7-8104-36ce71d33158.png)

**Comment by julien51** [comment]
Ha! We had DNS issues then... they lasted for a couple hours before being fixed.
