### ISSUE TITLE
Get a response code 204 when submit a ping POST to hub

### ISSUE THREAD

**Issue by sonphnt** [superfeedr/documentation#115]
Hi,

I have just tried to use this service as Rss Hub with real time feature. Everything seems correct but I dont know why I got 204 return when I submit a POST to my hub located at superfeedr.com. I am not quite sure if the server has received my ping or not.

What code 204 means ?
From Inoreader, I can see my subscription to feed URL turned to "Realtime". And try to ping to the hub and get 204 by using PostMan tool.

Do I need to do anything else from InoReader or basically just add my FeedURL?

How can I verify if the hub has received my ping?

Thanks

**Comment by julien51** [comment]
Hello and sorry for the terribly late response... 204 is the expected status.
