### ISSUE TITLE
Is X-Hub-Signature correct for content distribution requests?

### ISSUE THREAD

**Issue by johnspurlock** [superfeedr/documentation#116]
I'm not able to verify the signature on content distribution requests POSTed to my callback.

Content-Type: `application/atom+xml; charset=UTF-8`
X-Hub-Signature: `sha1=<sig-hex>`

Unable to recompute the same sig in java with `hmacsha1(post-request-body-as-utf-8-bytes, hub-secret-as-utf-8-bytes)`

Is this working for anyone?

**Comment by julien51** [comment]
Hello, I am sorry for the late response. 
The issue most of the time is due to encoding: people are computing the signature on encoded data (utf-8) when it needs to be computed on "raw bytes", before applying any encoding!

**Comment by johnspurlock** [comment]
I just looked into this again, and turned my hub signature verification back on.  The X-Hub-Signature coming in for recent content distribution requests match what I'm computing, so I'll close this issue out for now.  Thanks!
