### ISSUE TITLE
duplicate feeds

### ISSUE THREAD

**Issue by nandakishorereddy-chundi** [superfeedr/documentation#119]
Hi,
    I am generating RSS feed for websites which do not provide RSS with the help of "https://feedity.com". I am using that RSS feed for HUB.TOPIC in subscriptions and my end point for HUB.CALLBACK. In your documentation i found that you will send the whole json packet only if there is difference in signature assigned to those json packets. So i want a confirmation from your end that it is assured that i don't encounter duplicate packets.

**Comment by julien51** [comment]
You may always see "duplicate" notifications, because we would err on the side of sending the same data twice rather than not sending it at all. Please make sure you account for this on your end.
