### ISSUE TITLE
Unable to retrive feeds from https url

### ISSUE THREAD

**Issue by NavyaVullanki** [superfeedr/documentation#121]
Hello,
We have subscribed our RSS feeds to superfeedr. Superfeedr is able to retrieve the feeds from the http url but not from https. Below are the feed urls:
https://dts.fsa.usda.gov/feeds/rss/USDA-FSA-Public/news-releases/?hostname=www.fsa.usda.gov
https://fsa.blogs.govdelivery.com/feed/

We are able to retrieve feeds for both the above urls with 'http'. Can you please help us in getting retrieving the feeds successfully over https urls as well?

Thanks in advance!

**Comment by julien51** [comment]
I am not sure I understand the full question. but in order to retrieve the content of feeds you first need to subscribe to them.
Have tou susbcribed to both feeds using both http AND https (URLs with different scheme would be considered 2 different URLs)...

**Comment by NavyaVullanki** [comment]
Thanks for the response. Also can you please respond to our issue#122 as that is a very high priority issue for us.

Regarding this issue: Yes we have subscribed to both the http and https. Http is working fine but not the one with https. Here are our subscriptions:

http://dts.fsa.usda.gov/feeds/rss/USDA-FSA-Public/news-releases/?hostname=www.fsa.usda.gov
http://fsa.blogs.govdelivery.com/feed/ 
https://dts.fsa.usda.gov/feeds/rss/USDA-FSA-Public/news-releases/?hostname=www.fsa.usda.gov 
https://fsa.blogs.govdelivery.com/feed/
