### ISSUE TITLE
Deleted Feed is still showing up

### ISSUE THREAD

**Issue by NavyaVullanki** [superfeedr/documentation#122]
This is a high Priority issue as the deleted feeds are not getting updated in Superfeedr and we are using this on our home page.

We have subscribed to superfeedr to retrieve feeds for: 
http://dts.fsa.usda.gov/feeds/rss/USDA-FSA-Public/news-releases/?hostname=www.fsa.usda.gov

Our User account is: Fsawebservices
Email ID:  fsawebservices@gmail.com

We are able to retrieve feeds successfully. We have added a old test feed and deleted that after our testing is done from the FSA RSS News feeds. But superfeedr is still caching that deleted feed. How can we refresh or force Superfeeder to read top/latest 5 updated feeds?

Currently our FSA RSS feeds has the following feeds as top 5:
•http://www.fsa.usda.gov/news-room/news-releases/2017/nr_20171201_rel_0148
•http://www.fsa.usda.gov/news-room/news-releases/2017/nr_20171127_rel_0151
•http://www.fsa.usda.gov/news-room/news-releases/2017/nr_20171101_rel_0142
•http://www.fsa.usda.gov/news-room/news-releases/2017/nr_20171031_rel_0141
•http://www.fsa.usda.gov/news-room/news-releases/2017/nr_20171030_rel_0140

But Superfeeder is picking the following as top 5:
•http://www.fsa.usda.gov/news-room/news-releases/2014/nr_20140117_rel_0009-copy
•http://www.fsa.usda.gov/news-room/news-releases/2017/nr_20171201_rel_0148
•http://www.fsa.usda.gov/news-room/news-releases/2017/nr_20171127_rel_0151
•http://www.fsa.usda.gov/news-room/news-releases/2017/nr_20171101_rel_0142
•http://www.fsa.usda.gov/news-room/news-releases/2017/nr_20171031_rel_0141

We have already deleted nr_20140117_rel_0009-copy from our FSA website a week ago but superfeedr is still caching it.

Thanks in advance!

Thanks
Navya

**Comment by julien51** [comment]
Hello,

I am sorry about the confusion but what you're asking is not the way RSS feeds work... When a service subscribes to your feed thru us our directly, they will have access to all the stories added to the feed over time. Since feeds are "windows" of content, when a story is not in the feed anymore, it does not mean that they will delete the story from their servers.

This is exactly how superfeedr works: we find new stories added to the feed and store them. When you add more, we store more, but we are unable to "delete" past stories on your behalf.

**Comment by NavyaVullanki** [comment]
Thank you! 
As a work around for this issue we have subscribed to the url: 
http://dts.fsa.usda.gov/feeds/rss/USDA-FSA-Public/news-releases/?hostname=www.fsa.usda.gov&perc-tid=
 but I do not see any feeds from the superfeedr Push Console: 
Request:
curl -G https://push.superfeedr.com/ -u fsawebservices:2ff7de79a6436e6cbb8321193e92c4b4 -d 'hub.mode=retrieve' -d 'hub.topic=http://dts.fsa.usda.gov/feeds/rss/USDA-FSA-Public/news-releases/?hostname=www.fsa.usda.gov&perc-tid=' -d 'hub.callback=https://push.superfeedr.com/dev/null' -d 'count=5' -d 'format=json'

Response:
200 Successcontent-type: application/json; charset=utf-8
{
  "status": {
    "entriesCountSinceLastMaintenance": 0,
    "velocity": 0,
    "popularity": 0,
    "pornRank": 0,
    "bozoRank": 0,
    "lastParse": 1513010991,
    "period": 360,
    "lastMaintenanceAt": 1513009057,
    "feed": "http://dts.fsa.usda.gov/feeds/rss/USDA-FSA-Public/news-releases/?hostname=www.fsa.usda.gov&perc-tid=",
    "lastFetch": 1513010991,
    "code": 200,
    "title": "News Releases",
    "nextFetch": 1513011351,
    "http": "Fetched (ring) 200 360 and parsed 0/226 entries"
  },
  "title": "News Releases",
  "updated": "",
  "standardLinks": {},
  "items": []
}
![2017-12-11_11-41-59](https://user-images.githubusercontent.com/11925461/33842742-6cb43532-de69-11e7-85f6-fbab21623e09.png)
