### ISSUE TITLE
Any way to pass an authorization token Header for subscription webhook url

### ISSUE THREAD

**Issue by carolegodfrey** [superfeedr/documentation#124]
Hello,

We are trying to set up a superfeedr subscription that uses a travis url as SUBSCRIPTION WEBHOOK URL (HUB.CALLBACK) to trigger a travis build (as described in the following link)
https://docs.travis-ci.com/user/triggering-builds
We have been unsuccessful as the travis callback requires an Authorization header token. Is there any way to specify headers for a subscriptions hub.callback? We have been setting up New Subscriptions via the console.

Thanks In Advance

**Comment by julien51** [comment]
Unfortunately at this point it is not possible to customize the headers sent in notifications... We would also explicitly discourage that because we would not guarantee that these credentials would be stored in a way that would make them 100% secure.
