### ISSUE TITLE
Avoid showing description as title by missing <title>

### ISSUE THREAD

**Issue by maltsev** [superfeedr/documentation#126]
In my RSS feeds items doesn't have `<title>`. Once I integrated Superfeedr as a publisher with my feeds RSS readers (e.g. Feedly, Inoreader) started showing content from `<description>` as item titles ([like this](https://user-images.githubusercontent.com/923973/36265360-befc4ff4-1277-11e8-847a-31c21de1c925.png)). Is there a way to avoid that and just keep the title empty?

Here is an example of my RSS feed:
```xml
<?xml version="1.0" encoding="UTF-8"?>
<rss xmlns:content="http://purl.org/rss/1.0/modules/content/" xmlns:atom="http://www.w3.org/2005/Atom" version="2.0">
  <channel>
    <title>Test</title>
    <link>https://my.domain/</link>
    <description>Test</description>
    <pubDate>Tue, 13 Feb 2018 16:39:11 +0000</pubDate>
    <lastBuildDate>Tue, 13 Feb 2018 16:39:11 +0000</lastBuildDate>
    <ttl>360</ttl>
    <atom:link rel="hub" href="http://mydomain.superfeedr.com/"/>
    <atom:link xmlns:atom="http://www.w3.org/2005/Atom" href="https://my.domain/test.xml" type="application/rss+xml" rel="self"/>

    <item>
      <description><![CDATA[Test description9]]></description>
      <guid isPermaLink="false">9</guid>
      <pubDate>Tue, 13 Feb 2018 16:39:11 +0000</pubDate>
    </item>
  </channel>
</rss>
```

**Comment by julien51** [comment]
If I remember correctly the RSS and Atom spec actually require that items have a title... which is why we actually add try to add one which makes the most sense.

**Comment by maltsev** [comment]
@julien51 thanks for the quick response!

Not quite: 
> All elements of an item are optional, however at least one of title or description must be present.
> https://validator.w3.org/feed/docs/rss2.html

[The validator](https://validator.w3.org/feed/) also confirms that having only `<description>` is valid.
