### ISSUE TITLE
Superfeedr API sporadically down today

### ISSUE THREAD

**Issue by gduquesnay** [superfeedr/documentation#128]
I don't know if this is the right place to post this but I see other people posting supporty request here and getting supporty answers.

Today we started randomly getting "401 Unauthorized" responses from your API.  This is happening with curl but it also happens when we log into the site i.e. we have to refresh the page several times before our subscriptions show up.  We are currently evaluating superfeedr as a critical component of our architecture for an up coming product.  Are these API issues only affecting our account?  Is it something we did wrong while testing against the API and we are now somehow throttled and creating another account would resolve it? Is it an issue that is affecting all your accounts but it's temporary and you will have it fixed soon?

**Comment by somprabhsharma** [comment]
We are facing similar issue `401 Unauthorized` while subscribing using Superfeedr APIs since last 24 hours.

**Comment by gduquesnay** [comment]
It seems to be working again.  I'd be interested to know how often this happens.  Closing this issue for now though.
