### ISSUE TITLE
Is superfeedr receiving data via "websub publishing" or are you polling the subscriptions?

### ISSUE THREAD

**Issue by gduquesnay** [superfeedr/documentation#131]
We've subscribed to several feeds and we suspect few if any are using websub to publish their updates to superfeedr.  Somehow we are still getting webhooks with data from these feeds though.  We've tried subscribing to a few of the same feeds via http://pubsubhubbub.appspot.com/ and https://switchboard.p3k.io/docs  (the only other websub hub services we could find) but we weren't able to get back any data from them our assumption being that we couldn't get data because none of the feed were publishing to them.

**Comment by jcabral** [comment]
http://pubsubhubbub.appspot.com/ doesn't send you the updated data. Is alert you when to pull. 
Also superfeedr normalizes the data, sou you write only one code that works for all feeds.

**Comment by gduquesnay** [comment]
Thanks.
