### ISSUE TITLE
Incorrect feed / subscription count

### ISSUE THREAD

**Issue by mvoltolina** [superfeedr/documentation#132]
Hello,

the feed / subscription count does not match the actual number of subscriptions. Screenshot attached.

Thank you.
![screen shot 2018-05-06 at 6 37 28 am](https://user-images.githubusercontent.com/960429/39672448-2f3a9da2-50f8-11e8-88b6-c98366e8e9a2.png)

**Comment by jcabral** [comment]
Same here. 
But already fixed.

**Comment by mvoltolina** [comment]
Mine has been showing 3 total but with zero in the actual list.

**Comment by mvoltolina** [comment]
Never mind, now fixed.
