### ISSUE TITLE
Can't unsubscribe feeds

### ISSUE THREAD

**Issue by jcabral** [superfeedr/documentation#133]
We cant unsubscribe feeds. 

I am trying via dashboard, but it doesn't let me. 
Unsubscribe buttons is disable. 

Already sent mails to @julien51 10 days ago, but nothing so far. 
![image](https://user-images.githubusercontent.com/64379/39958062-ec4b726a-55d3-11e8-89af-fd23202bcff9.png)

**Comment by julien51** [comment]
This was a bug that we identified and fixed. The fix is being deployed and it should be done in the next couple hours.
