### ISSUE TITLE
Multiple aggregated feeds

### ISSUE THREAD

**Issue by jbbae** [superfeedr/documentation#135]
Hi,

Is it possible to retrieve multiple aggregated feeds? So aggregations of aggregated feeds (each with a separate "callback" urls), depending on our users' preferences.

Specifically, we're creating an aggregated for each industry, and want to allow users to follow multiple industries.

Thanks so much for your help!

**Comment by julien51** [comment]
Yes! This is defintely an option in our API both for notifications and for retrieve calls.
