### ISSUE TITLE
ping to superfeedr doesn't trigger proper notification to subscribers

### ISSUE THREAD

**Issue by cyber007** [superfeedr/documentation#137]
HI we are integrating our RSS feed with your superfeedr hub service, finished Discovery and Ping steps.  However, on our dashboard, while we can see successful ping each time, but I don't see notification gets sent out to our subscribers consistently, only once at the same time of the received ping, but not at any other pings.  Do you know what could cause the notification not sent out timely?

acorns.superfeedr.com is the our hub name, and I am using the following curl command to manually ping:
curl -i -d "hub.mode=publish&hub.url=https://grow.acorns.com/-/custom/feed.xml" http://acorns.superfeedr.com/

**Comment by julien51** [comment]
Pings are only propagated for subscribers. Can you send us the URL of a subscriber who is not getting he pings?
