### ISSUE TITLE
Feed response limitation and not update

### ISSUE THREAD

**Issue by AvihayAshush** [superfeedr/documentation#138]
Hi 
We subscribe to MRSS feed with 100 items and get in the retrieve response only 10 items,
Also we didn't get any update on feed with heavy updates, not even see any update at 
PAST ENTRIES' IDS in you'r preview.

also thumbnail url that provided in <content> tag didn't return in the json only it return only under media group

**Comment by julien51** [comment]
Do you mind sending the feed URL?
