### ISSUE TITLE
What is superfeedr compared to RSS/Atom

### ISSUE THREAD

**Issue by buhtz** [superfeedr/documentation#140]
After reading the documenation it is still unclear for me what Superfeedr really is.

All features described in the docu is still implemented with regular RSS/Atom feeds.

So what is the difference? Why do I need Superfeedr?

**Comment by jcabral** [comment]
Superfeedr implements a PubSubHubbub protocol. So it posts your endpoint when a remote RSS is updated.

**Comment by buhtz** [comment]
Can you describe this in a more real use case please. I still do not get it. Sorry! :)

**Comment by jcabral** [comment]
Sure, I have a real time monitor for local news. 
Insted of pulling an RSS every X minutes, superfeed push me whenever there is an update.

**Comment by buhtz** [comment]
I see. Sounds like it transform Newsfeed as pull-medium back to a push-medium, right?

**Comment by julien51** [comment]
Exactly we're an RSS API which lets you wait for the data to come your way rather than poll for new updates.

**Comment by buhtz** [comment]
Than you missunderstood the main trigger of the invention name newsfeed/webfeed.

I understand the wish for a push-medium but you shouldn't cripple the newsfeeds standard for that. You could create your own standard/protocol.
