### ISSUE TITLE
Your Dashboard page returns a 500 error. Same happens on Subscriptions.

### ISSUE THREAD

**Issue by aggela** [superfeedr/documentation#142]
![image](https://user-images.githubusercontent.com/7797649/60418385-725f9f80-9beb-11e9-8244-2db2fa3b8fcc.png)

**Comment by bencomp** [comment]
See also #141

**Comment by fab10m** [comment]
I have the same problem

**Comment by bencomp** [comment]
For me the issue seems to have been resolved.
