### ISSUE TITLE
unable to get items from RSS feeds seemingly created with Well-Formed Web RSS Module

### ISSUE THREAD

**Issue by aggela** [superfeedr/documentation#143]
We have had this issue with various customers not able to send their RSS feed data in Moosend newsletters. The common denominator seems to be that they are created with Well-Formed Web RSS Module.

I have also emailed your support with information, yesterday, as I did not wan to disclose the RSS feed url of a customer in a public GitHub. Should you need further information, please contact me at aggela@moosend.com

<next_fetch>1970-01-19T01:52:47.800Z</next_fetch>
   <title>TitleRemovedByMe</title>
   <period>900</period>
   <last_fetch>1970-01-19T01:52:46.900Z</last_fetch>
   <last_parse>1970-01-19T01:52:36.887Z</last_parse>
   <last_maintenance_at>1970-01-19T01:52:36.890Z</last_maintenance_at>

Using any online RSS reader, I get the data fine.

**Comment by julien51** [comment]
Thanks,we'll get back to you by email shortly!
