### ISSUE TITLE
Etsy subscription is returning the empty response

### ISSUE THREAD

**Issue by mukhtar-gosaas** [superfeedr/documentation#144]
Hi,

We have been subscribed for the following web hook successfully: https://etsy.superfeedr.com/?hub.mode=subscribe&hub.topic=http://www.etsy.com/api/push/shops/shop_name/listings/latest.atom&hub.callback=***********&api_key=********

After subscription our end point is hitting successfully but we are receiving the empty response in our callback function. I contacted to "Etsy Developer Support" platform and got the suggestion to contact directly with Superfeedr that's why i am creating this issue.

Can you provide me some suggestion on it? and my email is mukhtar@gosaas.io

**Comment by julien51** [comment]
These are not empty... Please red this https://blog.superfeedr.com/http-raw-body/

**Comment by mukhtar-gosaas** [comment]
Thanks for your guidance and now we can process the response but we are receiving some basic attributes information instead of the complete information of the product.

Can you guide me what i have to do to get the all attributes information?

**Comment by utgs** [comment]
Greetings,
We are successfully getting the data required. I have one question though. Does Superfeedr also send data when someone buys a product from the shop (for which we have registered a webhook) and its quantity decreases by 1 or 2 (depending upon the number of items bought)?
