### ISSUE TITLE
Superfeedr.com website links are broken

### ISSUE THREAD

**Issue by kamicollo** [superfeedr/documentation#145]
At the moment, trying to login to superfeedr.com (https://superfeedr.com/login) returns Bad gateway 502 error. Same thing with a sign-up link and a few others.

![image](https://user-images.githubusercontent.com/591292/82119144-1a0b9f00-97b7-11ea-8feb-238bc32c8189.png)

**Comment by bencomp** [comment]
It looks like the insecure HTTP address does work, but we wouldn't use that to log in of course. I was surprised that the site doesn't always redirect from HTTP to HTTPS.
