### ISSUE TITLE
Problem with push notification on Medium

### ISSUE THREAD

**Issue by lampardlamps** [superfeedr/documentation#147]
hi there, 
I tried to set up a webhook on http://medium.superfeedr.com for push notification of https://blog.medium.com/feed but it keeps returning '422 Please provide a valid hub.topic (feed) URL that is accepted on this hub. This url could not be fetched.' It was okay until last week...Could you look into this pls? Thanks.

**Comment by alesito85** [comment]
Any particular way to resolve this?
