### ISSUE TITLE
Superfeedr fetch blocked by dev.to

### ISSUE THREAD

**Issue by smerchan** [superfeedr/documentation#149]
https://dev.to/feed/

FEED TITLE (ONLY FOR FEEDS):
STATUS MESSAGE: Fetched (ring) 403
LAST HTTP STATUS CODE: 403

The fetch from dev.to is forbidden. It appears superfeedr is perhaps blocked by dev.to?

**Comment by gaganlokesh** [comment]
@smerchan Any update on this?

**Comment by julien51** [comment]
Hello, we've reached out to the team at dev.to who seems to have have blocked us.
