### ISSUE TITLE
lots of connection closed and connection refused errors

### ISSUE THREAD

**Issue by bbassett** [superfeedr/documentation#151]
Hello!

I work for a podcast host, and we have integrated with superfeedr, but we get frequent errors in our integration, the errors just show connection closed or connection refused. We are wondering, is there a rate limit? we have set up some retries to be able to get successful submissions, but we want to make sure that we aren't causing undue stress on your side. Is there a rate limit? or another reason why would be seeing a lot of errors?

thanks!

**Comment by eddiebarth1** [comment]
bump

We're seeing large numbers of network errors on requests & TCP connection refused over at Medium.  Any clarity around this would be a great help.

**Comment by da2x** [comment]
I emailed Superfeedr about this over a month ago, and haven’t heard back.

**Comment by julien51** [comment]
First of all, I am sorry about the delays here. I should be much better at looking at issues here. I will try to find a way to get notifications in emails when they happen.
Is there any way to get a bit more data about the issues you're seeing? We have monitoring in place but I suspect they happen at a "higher" level in the stack (maybe with our load balancer?). Any thing you can provide could be helpful!

**Comment by da2x** [comment]
>  will try to find a way to get notifications in emails when they happen.

Click Watch at the top of the page (next to Star and Fork), and select Custom: Issues.
