### ISSUE TITLE
Lots of failed subscriptions

### ISSUE THREAD

**Issue by VladYermakov** [superfeedr/documentation#152]
Hello!

We're currently getting big amount of subscription failures without any meaningful error details.
Can you please check that?

Thanks in advance

P.S. I will try to add some details if I'll found them (for now that's simply empty response body so we can't correctly handle such errors)

**Comment by julien51** [comment]
Hello!
I am sorry for the delay here. Do yuu have a way to provide us with a bit mire info?
Thanks
