### ISSUE TITLE
strange answers to subscription requests

### ISSUE THREAD

**Issue by polyakoff** [superfeedr/documentation#27]
Hello!

I'm trying to add several hundreds of feeds from craigslist to superfeedr sending requests to https://push.superfeedr.com/

All the feeds are from one website and I have doublechecked that links are correct and feeds work as expected. I have set up my app to receive answer in json and then sending another request. For nearly first 300 feeds I get this result:

{"code": "200", "body": "{"status":{"period":4,"code":null,"lastMaintenanceAt":1215824721,"nextFetch":1399800160,"lastFetch":1238451905,"lastParse":1238451905,"feed":"<link to feed>","http":""},"title":null,"items":[]}"}

and for all the rest:

{"code": "200", "body": "{"status":{"period":3600,"code":404,"lastMaintenanceAt":1399756961,"nextFetch":1399762306,"lastFetch":1399758706,"lastParse":1238451905,"feed":"<link to feed>","http":"Fetched (ring) 404 3600"},"title":null,"items":[]}"}

The response status code is ok - 200, but how to explain that difference in responses and what does "Fetched (ring) 404" mean?

I've tried to find the answer in the documentation, but found only this:

> Superfeedr will return 200 with the content if we could retrieve the feed’s past entries.
> If you are not subscribed to the feed or if the feed has not yet been added to Superfeedr, we will return a 404.

and it does not help much.

Also I'm curious what does getting feeds in realtime means (how often does superfeedr perform feeds polling). Haven't found this info in docs too, looks like this info is stored in these json parameters I've got, but idk how to get it. I expected that superfeedr will get info about new feeds exactly after user had added them, but it looks like it happens periodically and user cannot control this feature.

Thanks in advance!

**Comment by danielhardy** [comment]
I am seeing this problem as well. Can you post a resolution in this thread so others understand? I like @polyakoff am seeing the "Fetched (ring) 404" and would guess it is related to the blocking but want to verify as that was 4+ years ago.

Any help is appreciated,

Daniel

**Comment by julien51** [comment]
Daniel, what's the feed url?

**Comment by danielhardy** [comment]
An example would be
http://phoenix.craigslist.org/search/cta?autoMakeModel=Porsche%20911&srchType=T&format=rss

**Comment by julien51** [comment]
HA, indeed, we are not able to retrieve Craiglists feeds. They are blocking us.

**Comment by danielhardy** [comment]
OK Thank you for the update. I'll assume this isn't going away as it has been 4 years

PS - Great to see you responding so quickly... makes me want to use the service even more. :+1:

**Comment by joefiorini** [comment]
@julien51 I just tried to subscribe to a craigslist feed and apparently this is still the case. What a disappointment, why would craigslist block a service like this? Isn't the point of a feed that is should be consumed?

**Comment by joefiorini** [comment]
IANAL, but on further research it appears that using the RSS feeds in any automated way might violate CL's terms of use. Bummer.

**Comment by julien51** [comment]
Sorry for th delay... indeed, CL is extremely picky when it comes to using their RSS feeds :(
