### ISSUE TITLE
Duplicate Notifications

### ISSUE THREAD

**Issue by mujtaba3B** [superfeedr/documentation#34]
We're trying to figure out why the same notification is being sent to us twice, hours apart in the cases I have seen. My understanding from reading the docs is that there are 3 retries within a very short span. If the retries do not yield a 200, the notification is expected to be retrieved by us using the retrieve endpoint. We are returning a 200 on the initial notification yet receiving the duplicate notification.

Here is a gist showing what we received from your end: https://gist.github.com/mujtaba3B/d236f87273078aaa2db8. 
A duplicate item is highlighted, as is the time when the request came in. I'm also not sure why "items" is included twice with the exact same content in both (within a single set of post params).

Can you shed some light on my confusion?

**Comment by gduquesnay** [comment]
Just started using superfeedr and we are seeing duplicates so it looks like this issue is still unresolved.  We are handling on our end also.
