### ISSUE TITLE
Clarify documentation of HTML Fragment subscriptions

### ISSUE THREAD

**Issue by barnabywalters** [superfeedr/documentation#40]
Currently there’s just a short sentence: http://documentation.superfeedr.com/subscribers.html#htmlfragments

A good start would be to link to/copy+paste http://blog.superfeedr.com/indieweb-microformats-fragments-subscriptions/, which gives an actual example.

I’m also left wondering what the behaviour is for multiple comma-separated selectors (or if they’re even supported), e.g. `#.h-entry,.h-event`

**Comment by pyk** [comment]
@julien51 For example, I try to subscribe to `https://news.ycombinator.com/newest#tbody%20tr.athing:first-child` and i got the following webhook payload

```
{"status":{"code":200,"http":"Parser Error mismatched tag","nextFetch":1445995799,"period":900,"lastFetch":1445994899,"lastParse":1238466305,"lastMaintenanceAt":1445992974,"feed":"https://news.ycombinator.com/newest#tbody%20tr.athing:first-child"},"standardLinks":{"shortcut icon":[{"rel":"shortcut icon","href":"favicon.ico"}]},"title":"","updated":null,"id":""}
```
Is this correct behaviour? I expect that the payload content some HTML portions as you described, but it's only contain that JSON schema.

**Comment by pyk** [comment]
@julien51 update: I change the subscription format to the default instead of JSON. Now works as expected.

**Comment by julien51** [comment]
HA! Yes, that's the bahvior we went for:

* if you specify a format (JSON or Atom) and we're unable to *convert* the source's format into it, we'll send you notitications in the required format, but indicating errors...
* if you do not specify a format, we send you the fragment (of whatever the original format is)
