### ISSUE TITLE
Retrieve by subscription endpoint!

### ISSUE THREAD

**Issue by julien51** [superfeedr/documentation#60]
Retrieving past entries per feed is great... but it would be also very useful to retrieve content by subscription endpoint (domain, url, jid... etc).

We should loop in @benwerd from @idno on this :)

**Comment by julien51** [comment]
Released! See [blog post](http://blog.superfeedr.com/retrieve-multiple-feeds/)!

**Comment by benwerd** [comment]
Coming to this a little late, but this is awesome!

On Thu, Mar 19, 2015 at 1:55 AM, Julien Genestoux <notifications@github.com>
wrote:

> Closed #60 <https://github.com/superfeedr/documentation/issues/60>.
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/superfeedr/documentation/issues/60#event-259111113>.
>



-- 
Ben Werdmuller
<http://goog_1933028737>
benwerd.com | werd.io

+1 (312) 488-9373
