### ISSUE TITLE
image link is missing in feeds produced by superfeeder

### ISSUE THREAD

**Issue by hishamBakr** [superfeedr/documentation#67]
Dear,
       I am new to superfeeder. I created a subscriber account. I subscribed to an rss:

http://www.masrawy.com/rssfeed/35/%D9%85%D8%B5%D8%B1-%D8%B3%D9%8A%D8%A7%D8%B3%D8%A9

original feeds have:
<image>
http://media.linkonlineworld.com/img/Thumb/2015/5/5/2015_5_5_0_12_46_333.jpg
</image>

but feeds I receive from superfeeder doesnt have image item. Please advise

**Comment by julien51** [comment]
Thanks @hishamBakr !

We actually normalize the data, which means we should be turning the  `<image>` into a `<link>` element in the notifications. Isn't that what you're seeing?

**Comment by hishamBakr** [comment]
Thank you for your response. No. the image is dropped at all. you can try with RSS I mentioned:

http://www.masrawy.com/rssfeed/35/%D9%85%D8%B5%D8%B1-%D8%B3%D9%8A%D8%A7%D8%B3%D8%A9

**Comment by julien51** [comment]
Ok, let us get back to you ASAP.

**Comment by julien51** [comment]
The feed does not see to be using the `<image>` element correctly. You can see details in the [feed validator](http://feedvalidator.org/check.cgi?url=http%3A%2F%2Fwww.masrawy.com%2Frssfeed%2F35%2F%25D9%2585%25D8%25B5%25D8%25B1-%25D8%25B3%25D9%258A%25D8%25A7%25D8%25B3%25D8%25A9).

We do expect `<image>` to be like this:

```xml
<image>
    <link>...</link>
    <url>...</url>
    <title>...</title>
</image>
```
We will try to see if we can still handle this but this will probably take a couple days.

**Comment by julien51** [comment]
@hishamBakr We're looking for more feeds which are similarly invalid before we implement this. Do you know of any other?

**Comment by hishamBakr** [comment]
Thank you for your support. I just discovered this feed only for now. If I found similar feeds, I will keep you updated.

**Comment by julien51** [comment]
@hishamBakr I'll close this issue for now because I think this is only specific to this very feed. If you find other feeds, please, feel free to re-open and publish the URLs so we can consider whether it's worth a change in our schema mapping.

**Comment by hishamBakr** [comment]
I am trying to make news app that target Arabic news sites. Actually almost all of Arabic news sites I tried have wrong RSS format :(

This is another example:
http://www.elwatannews.com/home/rssfeeds

this feed has image as
<image>&lt;img src='http://media.elwatannews.com/News/Small/267632_Large_20140913043935_19.JPG' align='right' /&gt;</image>

which is not understood by superfeedr.

I have other examples of Rss feeds that  have invalid Rss format such as:
http://www.shorouknews.com/rss/main/
http://www.youm7.com/rss/SectionRss?SectionID=65
