### ISSUE TITLE
Subscriber could not Subscribe

### ISSUE THREAD

**Issue by deepak-goodmethodsglobal** [superfeedr/documentation#68]
Even though, the curl request sent with hub.mode : subscribe, I am getting the response as :-"Please provide a hub.mode : subscribe|unsubscribe|publish"

**Comment by julien51** [comment]
Do you mind providing the exact request you're sending?

**Comment by deepak-goodmethodsglobal** [comment]
Thank you for your response Julien.
$params = array(
                        'hub.callback' => $this->callback,
                        'hub.mode' => $action,
                        'hub.topic' => $url,
                        'hub.secret' => urlencode(sha1($this->hubSecret))
                        );
        $ch = curl_init($this->apiUrl);
        $this->setCurlOptions($ch, array('Accept: application/json'));
        curl_setopt($ch, CURLOPT_POST, 1);
        curl_setopt($ch, CURLOPT_POSTFIELDS, $params);
        $res = $this->curlExec($ch);

I am using the above code to send request where
$this->callback = 'http://gmgwork.com/webhook/superfeedr/endpoint.php'
$action = 'subscribe'
$this->hubSecret = 'myHubSecret'
$url = 'http://push-pub.appspot.com/feed'
$this->apiUrl = 'https://push.superfeedr.com/'

Let me know whether you require any other information.

**Comment by julien51** [comment]
I'm not a PHP expert, but if [I believe this](http://stackoverflow.com/a/5676572/73987) you're not using the `curl` correctly. You need to convert `$params` into an urlencoded string.

**Comment by julien51** [comment]
Any progress on this?

**Comment by julien51** [comment]
I'm closing this for now as I have not heard back from you. Feel free to re-open if you're still unable to subscribe with PHP.

Thanks,

**Comment by deepak-goodmethodsglobal** [comment]
Sorry for the late replay Julien, I was on my vacation.
Yes the issue is solved.
Thank you for your support.
