### ISSUE TITLE
Image link is missing in feeds produced by superfeeder (re open)

### ISSUE THREAD

**Issue by ghost** [superfeedr/documentation#71]
You closed [my issue](https://github.com/superfeedr/documentation/issues/67) and I dont know how to reopen it. I am trying to make news app that target Arabic news sites. Actually almost all of Arabic news sites I tried have wrong RSS format :(

This is another example:
http://www.elwatannews.com/home/rssfeeds

this feed has image as
`<img src='http://media.elwatannews.com/News/Small/267632_Large_20140913043935_19.JPG' align='right' />` which is not understood by superfeedr.

I have other examples of Rss feeds that have invalid Rss format such as:
`http://www.shorouknews.com/rss/main/` and `http://www.youm7.com/rss/SectionRss?SectionID=65`

**Comment by hishamBakr** [comment]
this is another feed also that has invalid image entry
http://www.mawaly.com/rss/news/music

**Comment by hishamBakr** [comment]
I also found feed of type "Atom"  has image and superfeeder can't get it either as image entry or as a part of summary:

http://www.bbc.co.uk/arabic/index.xml

**Comment by julien51** [comment]
Thanks @hishamBakr We'll check this in more details now.

**Comment by hishamBakr** [comment]
Is there any update?
Also I discovered new issue:
http://www.almasryalyoum.com/rss/rssfeeds
the "published" field is null while it exists in feed.

**Comment by julien51** [comment]
Sorry about this @hishamBakr. 
Could you clarify the problem with http://www.bbc.co.uk/arabic/index.xml ?

For  http://www.almasryalyoum.com/rss/rssfeeds, there is no `<pubDate>` element in the `<item>` elements, so we don't show any:

```xml
<item>
      <link>
        http://www.almasryalyoum.com/news/details/777996
      </link>
      <a10:author>
        <a10:name>
          أ.ش.أ
        </a10:name>
      </a10:author>
      <title>
        «الأوقاف» تطالب بالتركيز على ضرورة تعاون المجتمع لمواجهة التطرف
      </title>
      <description>
        طالبت وزارة الأوقاف أئمة وخطباء المساجد بضرورة الالتزام بالإضافة التي ألحقتها الوزارة بالجزء الثاني في خطبة الجمعة القادمة للتركيز على ضرورة تعاون جميع أبناء المجتمع في كل ما يحقق له الأمن والأمان والرخاء والاستقرار، ومواجهة التطرف والمتطرفين فكريا وثقافيا. وأكد القطاع الديني بوزارة...&lt;br/&gt; &lt;p&gt;هذا المحتوى من «المصري اليوم».. اضغط &lt;a href='http://www.almasryalyoum.com/news/details/777996'&gt;هنا&lt;/a&gt; لقراءة الموضوع الأصلي والتعليق عليه&lt;/p&gt;
      </description>
    </item>
```

There's one at the `<channel>` level, but that does not imply anything when it comes to the `<item>`s. (per [the spec](http://cyber.law.harvard.edu/rss/rss.html#ltpubdategtSubelementOfLtitemgt), it's actually only an item sub-element.)
