### ISSUE TITLE
Endpoint change

### ISSUE THREAD

**Issue by mujtaba3B** [superfeedr/documentation#73]
When did the endpoint change from superfeedr.com/hubbub/ to push.superfeedr.com?

**Comment by julien51** [comment]
Hello,
Hum.. on [November 14th 2013](http://blog.superfeedr.com/push-endpoint/)... Also, we added warnings to the API for the whole time and performed a redirect to the new page.

**Comment by mujtaba3B** [comment]
Thanks!
