### ISSUE TITLE
Using Superfeedr with Phonegap

### ISSUE THREAD

**Issue by kmadill** [superfeedr/documentation#78]
Hello,

The Superfeedr API is working well in my mobile application when simulated in the browser using Ripple. 

However, when I attempt to use it natively on the device, the API no longer returns any data. Is this a known issue or is there additional settings that need to be configured?

Thanks!

**Comment by julien51** [comment]
I don't know of any specific issue with mobile/PhoneGap.
Are you able to provide more data as to what is going on? An erorr message?

**Comment by julien51** [comment]
Hi, any news on this?
