### ISSUE TITLE
Pricing for using Superfeedr's Null device

### ISSUE THREAD

**Issue by kavishml** [superfeedr/documentation#79]
When I use superfeedr's Null device as my callback url am not able to find details about the pricing in the documentation. For my requirements I don't really need any push notifications. So is there way to switch of real time notifications and use only the retrieve call according to my requirements? If that is possible what would be the pricing model then?

**Comment by cafuentes** [comment]
I'm also interested in the answer to this question.

**Comment by julien51** [comment]
Whether you use the null device or not, the pricing is the same it's based on the number of times we would send a notification, in other words: it's based on the number of changes in the feed.

It's proabably not obvious, bu you have to remember that our pricing was setup in a time where [PUSH was the only way to use Superfeedr](http://blog.superfeedr.com/ways-to-use-superfeedr/).

We are working on a feed based pricing as well to reflect your use case.
