### ISSUE TITLE
number of items to retrieve

### ISSUE THREAD

**Issue by dterrazas** [superfeedr/documentation#80]
I am using the superfeedr.js file and cannot seem to get it to retrieve more than 5 entries.  I have set the following loadedEntries value (See Below).  Is there another variable somewhere for this?

Feed: function Feed(url) {
		this.loadedEntries = 10;
		this.feedFormat = 'json';

But still I only get 5

Feed URL: http://blogsites.colgate.edu/feed/?cat=-5

**Comment by julien51** [comment]
Hi! Do you mind sharing your Superfeedr login username? I could not find any subscription to http://blogsites.colgate.edu/feed/?cat=-5 in our database?

Generally, we only store entries from a feed from the moment we *know* about that feed (i.e. when at least one user has subscribed to it). This means that if you're the first subscriber to this feed, we can only serve at most the current number of entries in the feed.

**Comment by dterrazas** [comment]
Superfeedr login username: applicationdeveloper

Sorry subscription name is: http://blogsites.colgate.edu/?feed=rss2
<https://superfeedr.com/users/applicationdeveloper/subscriptions#modal_subscriptions_12>

On Fri, Dec 4, 2015 at 7:17 AM, Julien Genestoux <notifications@github.com>
wrote:

> Hi! Do you mind sharing your Superfeedr login username? I could not find
> any subscription to http://blogsites.colgate.edu/feed/?cat=-5 in our
> database?
>
> Generally, we only store entries from a feed from the moment we *know*
> about that feed (i.e. when at least one user has subscribed to it). This
> means that if you're the first subscriber to this feed, we can only serve
> at most the current number of entries in the feed.
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/superfeedr/documentation/issues/80#issuecomment-161953669>
> .
>



-- 
David Terrazas
Web Designer/Developer
Colgate University
450H Case/Geyer
315-228-6586 or 315-719-7435


*The sun, with all those planets revolving around it and dependent on it,
can still ripen a bunch of grapes as if it had nothing else in the universe
to do. *
*Galileo Galilei *

**Comment by julien51** [comment]
Well, we do have more than 5 items stored for this feed, so you should be able to get more... Did you check the code you're using to make sure that it's actually asking for more than 5 items?

Feel free to post your files here.

**Comment by dterrazas** [comment]
I just changed the code to **20** entries from **10** entries in the file _superfeedr.js_

I have tried uploading files of type **".zip"**  and **.ZIP** but I receive a warning 
**Unfortunately, we don’t support that file type**

**Comment by dterrazas** [comment]
Does it take time for your server to update?  I change the code yesterday to 10 entries and now that is working after about 24 hours.  But when I changed it to 20 entries a few minutes ago, it still only displays 10 posts/entries.  It was originally only showing 5....

**Comment by julien51** [comment]
There are no update on the server... however, at this point we only have 10 entries stored for this feed, so you can't ask for 20!

**Comment by dterrazas** [comment]
I did ask for 20 but I still only get 10.

**Comment by julien51** [comment]
Yeah, and you will only get 10 for as long as the feed does not publish more items!

**Comment by dterrazas** [comment]
So I added a new post and published it.  Should I wait...because right now it returns nothing

**Comment by julien51** [comment]
Nothing or just the previous 10 items? 
We should be able to detect the new item within 15 minutes of when you added it. Then, if you request 20 items, you'll get 11.
