### ISSUE TITLE
IE 9 Access Denied issue

### ISSUE THREAD

**Issue by NavyaVullanki** [superfeedr/documentation#81]
Feed method is working fine in all other browsers except IE9 and below. 
I see "Access Denied" error on the xmlHTTP.ope("get",endpoit,true) methoid.

I tried using the XDomainRequest instead of XMLHTTPRequest but still it did not work.

I tried setting the below empty Listeners as well but, still its thrwoing the same error.

                       xmlHttp.onprogress = function () { };
                        xmlHttp.ontimeout = function () { };

                       setTimeout(function () {
                            xmlHttp.send();
                        }, 1000);

Thanks
Navya

**Comment by julien51** [comment]
I'm sorry for the delay. Could you send the full code you're using?
Thanks
