### ISSUE TITLE
ASP.NET WebHooks

### ISSUE THREAD

**Issue by cannilsson** [superfeedr/documentation#83]
Having some issues with getting ASP.NET WebHooks talking to Superfeedr. Has anyone tackled this combination? Thanks.

**Comment by julien51** [comment]
Hum. What are the problems you're facing? I have not heard of any specific ASP.NET issues.
Please, give a little more info if you can!

**Comment by cannilsson** [comment]
There is no out-of-the-box ASP.NET Webhooks Receiver available for Superfeedr (http://blogs.msdn.com/b/webdev/archive/2015/09/04/introducing-microsoft-asp-net-webhooks-preview.aspx), and I don't seem able to get the GenericJson ASP.NET Webhooks Receiver to work with Superfeedr. This ASP.NET Webhooks implementation works seamless with Microsoft Azure for other Webhook Senders, which makes it my preferred solution (but I am open for alternatives). Thanks.
