### ISSUE TITLE
How to publish my atom feed?

### ISSUE THREAD

**Issue by czmarcos** [superfeedr/documentation#84]
Sorry for the basic question. I created a php file that generates the atom feed and my hub at superfeedr.

Now, I don't know how to publish my atom feed file (http://www.dubbi.com.br/feed.atom.php). I tried to make a request through this link below, but it didn't work (returns Please provide a hub.mode : subscribe|unsubscribe|retrieve|replay|list|status)

http://dubbi.superfeedr.com/?hub.mode=%22publish%22&hub.url=http://www.dubbi.com.br/feed.atom.php

Thanks

**Comment by julien51** [comment]
The "publish" mode needs to be a POST request (not a GET request). Also there is no need to wrap `publish` between `"`.
