### ISSUE TITLE
Some entries in feed have content element others do not... 

### ISSUE THREAD

**Issue by wrinkleydog** [superfeedr/documentation#86]
I've been testing with the following feed:  http://daringfireball.net/feeds/main.  If you retrieve the last 5 items for this feed you'll notice that some of the entries have the content element and others do not.  Looking at the source for this page they all have <content> and it's formatted the same for each item.  Why does superfeedr return content for some, but not for others?

**Comment by julien51** [comment]
Hello. 
I'm very sorry for the very long delay to get back to you.
I did a quick investigation and found that indeed some entries lack the `content` element. The most common reason for this is that the content of an individual entry is *too* large so we don`t store it. Now, this data is still pushed to your endpoint if you subscribed to the feed. You should see it in the payload.
