### ISSUE TITLE
Issue with Tumblr feeds?

### ISSUE THREAD

**Issue by jalada** [superfeedr/documentation#87]
I am subscribed to http://dontaskisis.tumblr.com/rss and it looks like Superfeedr thinks it is arbitrary content:

```
curl -G https://push.superfeedr.com/ -u xx:xx -d 'hub.mode=list' -d 'page=1' -d 'by_page=20' -d 'detailed=true' -d 'search[feed.url]=http://dontaskisis.tumblr.com/rss'
```

```
{
  "subscriptions": [{
    "subscription": {
      "format": null,
      "endpoint": "xxxx",
      "secret": null,
      "feed": {
        "status": {
          "code": 200,
          "feed": "",
          "http": "Fetched (ring) 200 180 and parsed arbitrary content",
          "lastParse": 1459359325,
          "period": 180,
          "lastMaintenanceAt": 1462357593,
          "nextFetch": 1462359744,
          "lastFetch": 1462359564,
          "entriesCountSinceLastMaintenance": 0,
          "popularity": 0,
          "velocity": 0,
          "bozoRank": 0,
          "pornRank": 0
        },
        "title": "just don't ask."
      }
    }
  }],
  "meta": {
    "total": 1,
    "page": 1,
    "by_page": 20,
    "search": {
      "feed.url": "http://dontaskisis.tumblr.com/rss"
    }
  }
}
```

**Comment by earlyriser** [comment]
Same result for a bunch of other tumblr subscriptions, like Instagram & Yahoo blogs, however RSS validator mark them as valid RSS: https://validator.w3.org/feed/check.cgi?url=https%3A%2F%2Fyahoo.tumblr.com%2Frss

I think this is an important fix because
1) It's generating 1000s of "We could not deliver..." notifications
2) Webhooks are not getting the RSS update information

**Comment by julien51** [comment]
Thanks for reaching out. Sorry for the delay to get back to you.
Let me inspect that in details, because indeed this seems strange.

**Comment by julien51** [comment]
We found the problem. We use `Accept` headers to indicate to Tumblr what type of content we accept.
Our header looks like this: application/atom+xml,application/rdf+xml,application/rss+xml,application/xml,text/xml,application/json,*/*`

Apparently, Tumblr yields us RSS but using the `application/json` Content-Type header.
Right now, we do not even try to parse the content when the Content-Type header is `application/json` (as we assume this is returned intentionally).

We'll try to add a custom rule (🙄) for Tumblr feeds...

You can try by doing this:
```
curl -H  'Accept: application/atom+xml,application/rdf+xml,application/rss+xml,application/xml,text/xml,application/json,*/*' "http://dontaskisis.tumblr.com/rss" -D- -o 
```

**Comment by jalada** [comment]
@julien51 funnily enough the content you then send in a fat ping to my Rails app also interprets it as `application/json` even though I don't think you send any kind of content header.

**Comment by julien51** [comment]
We do actually... for arbitrary content we forward what we get when fetching the feed!

**Comment by jalada** [comment]
Probably Rails hiding it from me.

**Comment by julien51** [comment]
This has now been fixed. You should see the past entries coming too... assuming they're still 'inside' the feeds.

**Comment by jalada** [comment]
Thanks @julien51! Looking good from here!
