### ISSUE TITLE
has the schema recently changed - I no longer get the item description from an RSS feed

### ISSUE THREAD

**Issue by Yabrfish** [superfeedr/documentation#91]
https://push.superfeedr.com/?hub.mode=retrieve&hub.topic=http%3A%2F%2Fbritishmarine.co.uk%2Frss-feeds%2Fnews&count=5&format=json&authorization=YW5keXN0ZXdhcmR1azpkYzM2MmEyMWE0ZmNlMTc3MjIzZWNiZjE2MGUwZmE1YQ%3D%3D&

**Comment by jawache** [comment]
Hia, i'm also not getting the items description in the feed (for most items), e.g. 

https://push.superfeedr.com/?authorization=amF3YWNoZTo3NWEwMzUzOWI5ZDg2YTQzZjkwYmJiN2JjNTYxZWMyMQ==&count=50&hub.mode=retrieve&format=json&hub.topic=http%3A%2F%2Ffeeds.feedburner.com%2FTEDTalks_video

Returns 50 items and only the last one has a summary field.

If you look at the raw RSS feed (http://feeds.feedburner.com/TEDTalks_video) each item still has a description tag and comparing the last item to the others i can't see any differences so I don't think it's an issue with a badly formatted item or character or anything, almost like superfeedr is ignoring the summary information for every item apart from the last.

**Comment by xlegs** [comment]
Same here for http://feeds.bbci.co.uk/news/world/rss.xml. No description.

**Comment by lesterchan** [comment]
Yeap, the same for me as well!
