### ISSUE TITLE
Problem with some feeds

### ISSUE THREAD

**Issue by finnmeier23** [superfeedr/documentation#95]
Hello, 

I want retrieve all items of a feed and save the items to my database. Because it is not possible to get more than 50 items per request i want to this with a while loop and get the first 50 items and the the next 50 items. But on my way to that i found some issues with superfeedr. I want retrieve 50 items of this feed: http://feed.aufwachen-podcast.de/audio but i get everytime only 10 items. And when i give superfeed the id from the item that i should get the items from 11-20 i don't get any items. So I think there is a problem with superfeedr that the items are not in your database. And with the feed: http://www.weltderphysik.de/podcast i have a problem as well, when i try to retrive the items i dont get any items. Can you pls look at those both feeds and say me what is the problem with them ?

**Comment by julien51** [comment]
We only store 50 items per feed... so paginating will not get your than 50 items.
