### ISSUE TITLE
Multiple hub.url documentation unclear

### ISSUE THREAD

**Issue by gRegorLove** [superfeedr/documentation#99]
Under Publishers > Ping:

> or by sending a coma separated list or url-encoded URLs like this hub.url=&lt;url1&gt;;&lt;url2&gt;.

Should it be "comma-separated list of..." or "semicolon-separated list of..."? The example shows the latter, but I wasn't sure.

**Comment by julien51** [comment]
Hey, sorry for the delay... the example is wrong, it should indeed be comas `,`! I'll fix this ASAP.
